openapi: 3.0.0
info:
  title: Movies api
  description: Movies api description
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: server of movie api
paths:
  /movies:
    get:
      summary: Returns a list of Movies.
      description: Retunrs a list of Movies with pagination.
      tags:
        - Movies
      paremeters:
        - in: query
          name: limit
          description: Defines a limit
          schema:
            type: string
      responses:
        "200": # status code
          description: Returns an array of movies
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
components:
  schemas:
    Movie:
      type: object
      required:
        - title
        - description
        - shotDescription
        - duration
        - releaseDate
        - images
        - genres
      properties:
        title:
          type: string
          example: Django
        description:
          type: string
          example: the description of the movie
        shotDescription:
          type: string
          example: A great movie of Tarantino
        duration:
          type: number
          example: 112
          description: duration of the movie in minits
        created_at:
          type: string
          example: 2020/10/12::00:20:30zzHH
        releaseDate:
          type: string
          example: 2015
        images:
          type: object
          required:
            - cover
          properties:
            cover:
              type: string
            poster:
              type: string
            captures:
              type: array
              items:
                type: string
        genres:
          type: array
          items:
            type: string
        actors:
          type: array
          items:
            type: string
        platformProduct:
          type: boolean